function Jon = get_Jo(in1)
%GET_JO
%    JON = GET_JO(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    09-Oct-2019 23:07:28

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = cos(q5);
t7 = sin(q1);
t8 = sin(q2);
t9 = sin(q3);
t10 = sin(q4);
t11 = sin(q5);
t12 = t3.*t4;
t13 = t3.*t9;
t14 = t4.*t8;
t15 = t8.*t9;
t16 = -t2;
t17 = t7.*t15;
t18 = -t15;
t19 = t2.*t12;
t20 = t2.*t13;
t21 = t2.*t14;
t22 = t7.*t12;
t23 = t2.*t15;
t24 = t7.*t13;
t25 = t7.*t14;
t27 = t15.*t16;
t28 = t13+t14;
t26 = -t22;
t29 = t12+t18;
t30 = t20+t21;
t31 = t24+t25;
t32 = t19+t27;
t33 = t17+t26;
Jon = reshape([0.0,0.0,1.0,t7,t16,0.0,t7,t16,0.0,t7,t16,0.0,t5.*t30+t10.*t32,t5.*t31-t10.*t33,-t5.*t29+t10.*t28,t6.*t7-t11.*(t5.*t32-t10.*t30),t6.*t16+t11.*(t5.*t33+t10.*t31),-t11.*(t5.*t28+t10.*t29)],[3,6]);
