function Jon = get_Jo(in1)
%GET_JO
%    JON = GET_JO(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    09-Oct-2019 23:05:55

Jon = reshape([0.0,0.0,1.0,0.0,0.0,1.0],[3,2]);
