function Jon = get_Jo(in1)
%GET_JO
%    JON = GET_JO(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Mar-2019 00:35:32

Jon = reshape([0.0,0.0,1.0,0.0,0.0,1.0],[3,2]);
