function T_base = get_0Tn(in1)
%GET_0TN
%    T_BASE = GET_0TN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    09-Oct-2019 23:05:54

q1 = in1(1,:);
q2 = in1(2,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = t2.*t3;
t7 = t2.*t5;
t8 = t3.*t4;
t9 = t4.*t5;
t10 = -t9;
t11 = t6+t10;
T_base = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,t2,t4,0.0,0.0,-t4,t2,0.0,0.0,0.0,0.0,1.0,0.0,t2,t4,0.0,1.0,t11,t7+t8,0.0,0.0,-t7-t8,t11,0.0,0.0,0.0,0.0,1.0,0.0,t2+t11,t4+t7+t8,0.0,1.0],[4,4,3]);
