function Jpn = get_Jp(in1)
%GET_JP
%    JPN = GET_JP(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    09-Oct-2019 23:05:54

q1 = in1(1,:);
q2 = in1(2,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = t2.*t3;
t7 = t2.*t5;
t8 = t3.*t4;
t9 = t4.*t5;
t10 = -t7;
t11 = -t8;
t12 = -t9;
Jpn = reshape([-t4+t10+t11,t2+t6+t12,0.0,t10+t11,t6+t12,0.0],[3,2]);
