function T = transformation(in1)
%TRANSFORMATION
%    T = TRANSFORMATION(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    09-Oct-2019 23:05:52

a = in1(:,1);
alpha = in1(:,2);
d = in1(:,3);
th = in1(:,4);
t2 = cos(alpha);
t3 = sin(alpha);
t4 = cos(th);
t5 = sin(th);
T = reshape([t4,t5,0.0,0.0,-t2.*t5,t2.*t4,t3,0.0,t3.*t5,-t3.*t4,t2,0.0,a.*t4,a.*t5,d,1.0],[4,4]);
